apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
        version: v1
    spec:
      containers:
      - name: jenkins
        image: custom-jenkins:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-pv-storage
          mountPath: /var/jenkins_home
        env:
        - name: JENKINS_SLAVE_AGENT_PORT
          value: "50000"
        - name: CASC_JENKINS_CONFIG
          value: /usr/share/jenkins/ref/casc_configs
      volumes:
      - name: jenkins-pv-storage
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
